### ISSUE TITLE
Unrelated file change triggers dependency rebuild

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#242] opened 2023-02-17 19:42 UTC
This is a continuation of # #194 , I guess.

I have a `./script/latency-test.sh` and whenever I change something in it, the whole dependencies are being rebuilt. I confirm with `find .` that the file in question is filtered out anyway.

`lib.buildDepsOnly` is being used, so it defaults to `lib.mkDummySrc`, AFAIU, so I don't even have much room to mess up things, I guess. But I do have rather elaborated setup with some minor issues that I need to address (see #241 ). But AFAICT they are not the cause.

**Comment by ipetkov** [comment] 2023-02-18 23:00
Could you provide a (hopefully minimal) reproduction I could take a look at?

I'm curious why the file is not being filtered out or if it's somehow getting pulled back in and invalidating the build :thinking:

**Comment by dpc** [comment] 2023-02-19 06:15
So I did some debugging and it comes down to 

```
          # copy over the linker/ar wrapper scripts which by default would get
          # stripped by crane
          dummySrc = craneLib.mkDummySrc {
            src = ./.;
            extraDummyScript = ''
              cp -r ${./.cargo} -T $out/.cargo
            '';
          };
```

in my `commonArgs` that I `commonArgs // {  ... rest of arguments to each crane-based derivation }`.

I forgot about it.

If I change the source to:

```
            src = filterWorkspaceDepsBuildFiles ./.;
```

where `filterWorkspaceDepsBuildFiles` is a function that strip the argument path from any unrelated files (even .rs ones, but that's irrelevant), I no longer get rebuilds.

So the question is - is it `mkDummySrc` issue, or am I using it incorrectly?

**Comment by dpc** [comment] 2023-02-19 07:00
Removing `extraDummyScript` doesn't help, so not it.

I got rid `dummySrc` and to use the `src = ./.;` only and the problem is still there.

I started new project and I can not reproduce. :confused:

**Comment by dpc** [comment] 2023-02-19 08:20
Here is the repro I was able to minimize:  https://github.com/dpc/crane-deps-rebuild-repro


```
nix build -L .#workspaceDeps # build
echo "foo" >> ./scripts/latency-test.sh # change the unrelated file
nix build -L .#workspaceDeps # why does this rebuild again?
```

I could probably minimize more, but I need to take some rest.

**Comment by ipetkov** [comment] 2023-02-19 21:41
Thanks for the repro!

It seems like changing _any_ file leads to the dependencies being rebuilt (including flake.nix). If I change `src = ./.;` to `src = craneLib.cleanCargoSource ./.;` the problem goes away :thinking: 

What's super weird is the source dummification is going to many lengths to avoid depending on the original source so I'm not sure why this is happening. Tried to look at the derivation file itself and I didn't see anything obvious (yet). Wonder if a string context is being kept when it should be discarded :thinking: 

I'll do some more testing on this, but for now it's possible to get unblocked by using an explicit source filter

**Comment by ipetkov** [comment] 2023-02-19 21:56
Definitely looks like a regression in crane, did a bisect and landed on 70fcce8db07c5121b02c2f1484768a3cff59edac.

Looks like the source name is the culprit, though not fully sure why as of yet

**Comment by ipetkov** [comment] 2023-02-19 22:03
Wow this is something, apparently `src` contains `/nix/store/9pf3shs0n2yryznijliprlb1lbq5rylw-qbm55f66wdwj5liahqcphlp4lrsz9ngc-source` I have no idea where the second hash can be coming form but it explains why the source name logic gets invalidated: changing any files in the repo makes the second hash change which causes a rebuild since the name of the output derivation would then change

**Comment by ipetkov** [comment] 2023-02-19 22:36
@dpc I think this will be fixed with https://github.com/ipetkov/crane/pull/248 but feel free to reopen and let me know if that's not the case!

**Closed** 2023-02-19 22:43 UTC

**Comment by dpc** [comment] 2023-02-20 01:06
I'm glad you've figured it out. I thought I'm going bananas. :D

**Comment by dpc** [comment] 2023-02-20 01:09
No more rebuilds with #248 . Fix confirmed on my end.

**Comment by Panke** [comment] 2023-02-27 09:44
Works for me as well. Thank you very much :-)
