### ISSUE TITLE
Multibin dummy stub regression

### ISSUE THREAD

**Issue by rvolosatovs** [ipetkov/crane#753] opened 2024-12-03 13:59 UTC
**Describe the bug**

An upgrade from da87d1af7e4e09fd0271432340a5cadf3eb96005 to 76d64e779e2fbaf172110038492343a8c4e29b55 introduced a regression for a crate with multiple binaries with following structure:
```
.
├── Cargo.lock
├── Cargo.toml
├── flake.nix
└── src
    └── bin
        ├── bye
        │   └── main.rs
        └── hello.rs
```

This is likely caused by https://github.com/ipetkov/crane/pull/752

**Reproduction**

here's an example crate that breaks:
https://github.com/rvolosatovs/nixify/tree/379112688c027532fd956444b284ade07e83aea8/examples/rust-hello-multibin

refs https://github.com/rvolosatovs/nixify/pull/314

**Comment by rvolosatovs** [comment] 2024-12-03 14:03
If it helps, here's logic I use to figure out all binaries that would be built by `cargo`: https://github.com/rvolosatovs/nixify/blob/379112688c027532fd956444b284ade07e83aea8/lib/rust/crateBins.nix#L1-L150

**Comment by ipetkov** [comment] 2024-12-04 04:03
Thank you for the report and the reproduction @rvolosatovs ! The issue was due to not deduping between discovered and declared bin targets, should be fixed with https://github.com/ipetkov/crane/pull/755!

**Closed** 2024-12-04 04:18 UTC
Labels: bug
