### ISSUE TITLE
Can't build workspace dependency from git repo with relative path references in Cargo.toml

### ISSUE THREAD

**Issue by mpontus** [ipetkov/crane#83] opened 2022-08-15 13:17 UTC
I'm trying to use crane to build a package dependent on on `polkadot-runtime` which is included in https://github.com/paritytech/polkadot/ repo and depends on several packages available in the same workspace. 

From [`runtime/polkadot/Cargo.toml`](https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/Cargo.toml):

```toml
xcm = { package = "xcm", path = "../../xcm", default-features = false }
xcm-executor = { package = "xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
xcm-builder = { package = "xcm-builder", path = "../../xcm/xcm-builder", default-features = false }
```

This presents a problem when, while building package dependencies, crane calls `downloadCargoPackageFromGit` to create a flat directory source containing all crates found in the git repo:

```nix
runCommandLocal "cargo-git" deps ''
  mkdir -p $out
  while read -r cargoToml; do
    local crate=$(toml2json <"$cargoToml" | \
      jq -r 'select(.package != null) | .package | "\(.name)-\(.version)"'
    )
    if [ -n "$crate" ]; then
      local dest="$out/$crate"
      cp -r "$(dirname "$cargoToml")" "$dest"
      chmod +w "$dest"
      echo '{"files":{}, "package":null}' > "$dest/.cargo-checksum.json"
    fi
  done < <(find ${repo} -name Cargo.toml)
''
```

Because the directory source does not reflect the structure of the original repository, create will not be able to resolve dependencies specified as relative paths, which in the following error when trying to build crate that depends on one of the workspace packages fetched from git:

```
error: failed to get `pallet-xcm` as a dependency of package `polkadot-runtime v0.9.24 (/nix/store/96wd59czjxqc7h7hka0mzl8a6qi7ld45-vendor-cargo-deps/fee86dd00aa0134a06a01f9b456af966945d77ffcf28dceb39cbd32320835532/polkadot-runtime-0.9.24)`
  ... which satisfies path dependency `wasm-project` of package `polkadot-runtime-wasm v1.0.0 (/build/dummy-src/target/release/wbuild/polkadot-runtime)`

Caused by:
failed to load source for dependency `pallet-xcm`

Caused by:
Unable to update /nix/store/96wd59czjxqc7h7hka0mzl8a6qi7ld45-vendor-cargo-deps/xcm/pallet-xcm

Caused by:
failed to read `/nix/store/96wd59czjxqc7h7hka0mzl8a6qi7ld45-vendor-cargo-deps/xcm/pallet-xcm/Cargo.toml`

Caused by:
No such file or directory (os error 2)
```

I hope this information is enough to identify the problem, but I can also draft a minimal reproducible example if it helps.

I have only brief familiarity with rust toolchain and development, but I'd happy to follow up on my diagnosis with a solution if you would point me in the right direction.

Thanks.

**Comment by mpontus** [comment] 2022-08-15 13:20
Sorry, GitHub ate my description. I will fix it and update the issue.

**Comment by ipetkov** [comment] 2022-08-15 15:59
Thanks for the report! I have two follow up questions:

1. Could you please provide either a link to a flake which exhibits the issue or a minimal reproduction of it?
2. If you were to manually run `cargo vendor` and use its configuration, does the project build successfully? If yes we should compare the differences in how it structures crates vs how `crane` does it

**Comment by dpc** [comment] 2022-08-15 23:45
I think this might have been an user error as well. My apologies.

**Comment by mpontus** [comment] 2022-08-16 13:21
@ipetkov Here's the flake that's failling on `nix build`: [https://github.com/mpontus/centrifuge-chain/blob/parachain/flake.nix](https://github.com/mpontus/centrifuge-chain/blob/parachain/flake.nix)

Running `cargo vendor` also creates a flat directory source, which seemingly contains all crates from git sources:

```sh
$ ls -l vendor/
drwxr-xr-x 3 mpontus users 4096 Aug 16 13:00 polkadot-runtime
...
drwxr-xr-x 3 mpontus users 4096 Aug 16 13:00 xcm
drwxr-xr-x 4 mpontus users 4096 Aug 16 13:00 xcm-builder
drwxr-xr-x 3 mpontus users 4096 Aug 16 13:00 xcm-emulator
```

And, after updating `.cargo/config.toml`, it fails with the exact same error when running `cargo build`:

```
error: failed to run custom build command for `polkadot-runtime v0.9.24 (https://github.com/paritytech/polkadot?branch=release-v0.9.24#22836e55)`

Caused by:
  process didn't exit successfully: `/home/mpontus/repos/centrifuge-chain/target/debug/build/polkadot-runtime-c62d0893e6a6adc4/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/home/mpontus/.rustup/toolchains/nightly-2022-05-09-x86_64-unknown-linux-gnu/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/home/mpontus/repos/centrifuge-chain/target/debug/wbuild/polkadot-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.62.0-nightly (cb1219871 2022-05-08)


  --- stderr
  error: failed to get `pallet-xcm` as a dependency of package `polkadot-runtime v0.9.24 (/home/mpontus/repos/centrifuge-chain/vendor/polkadot-runtime)`
      ... which satisfies path dependency `wasm-project` of package `polkadot-runtime-wasm v1.0.0 (/home/mpontus/repos/centrifuge-chain/target/debug/wbuild/polkadot-runtime)`

  Caused by:
    failed to load source for dependency `pallet-xcm`

  Caused by:
    Unable to update /home/mpontus/repos/centrifuge-chain/xcm/pallet-xcm

  Caused by:
    failed to read `/home/mpontus/repos/centrifuge-chain/xcm/pallet-xcm/Cargo.toml`

  Caused by:
    No such file or directory (os error 2)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `kusama-runtime v0.9.24 (https://github.com/paritytech/polkadot?branch=release-v0.9.24#22836e55)`

Caused by:
  process didn't exit successfully: `/home/mpontus/repos/centrifuge-chain/target/debug/build/kusama-runtime-967cb7ba63736667/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/home/mpontus/.rustup/toolchains/nightly-2022-05-09-x86_64-unknown-linux-gnu/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/home/mpontus/repos/centrifuge-chain/target/debug/wbuild/kusama-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.62.0-nightly (cb1219871 2022-05-08)


  --- stderr
      Blocking waiting for file lock on package cache
  error: failed to get `kusama-runtime-constants` as a dependency of package `kusama-runtime v0.9.24 (/home/mpontus/repos/centrifuge-chain/vendor/kusama-runtime)`
      ... which satisfies path dependency `wasm-project` of package `kusama-runtime-wasm v1.0.0 (/home/mpontus/repos/centrifuge-chain/target/debug/wbuild/kusama-runtime)`

  Caused by:
    failed to load source for dependency `kusama-runtime-constants`

  Caused by:
    Unable to update /home/mpontus/repos/centrifuge-chain/vendor/kusama-runtime/constants

  Caused by:
    failed to read `/home/mpontus/repos/centrifuge-chain/vendor/kusama-runtime/constants/Cargo.toml`

  Caused by:
    No such file or directory (os error 2)
```

**Comment by ipetkov** [comment] 2022-08-27 17:36
> And, after updating `.cargo/config.toml`, it fails with the exact same error when running `cargo build`:

Ah thanks for checking this, in that case this sounds like an issue with the upstream project. When using a git-dependency cargo _happens_ to check out the entire directory and so the build script gets lucky in assuming where other crates are located on the file system, but I believe this is an incorrect assumption. If the crate was published on crates.io and consumed from there I believe the same issue would occur.

I'm inclined to close this as an upstream problem given that there isn't much we can do to change how vendored crates are consumed by cargo, but feel free to reopen if there are other ideas.

**Closed by ipetkov** 2022-08-27 17:36 UTC

**Comment by mpontus** [comment] 2022-08-29 09:28
@ipetkov Understood, thanks for looking into this

**Comment by dzmitry-lahoda** [comment] 2022-10-04 18:15
@mpontus how you solved issue?

**Comment by dzmitry-lahoda** [comment] 2022-10-04 18:16
we can build polkadot like this 

```
{ pkgs, rust-nightly }:
with pkgs;
rustPlatform.buildRustPackage rec {
  # HACK: break the nix sandbox so we can build the runtimes. This
  # requires Nix to have `sandbox = relaxed` in its config.
  # We don't really care because polkadot is only used for local devnet.
  __noChroot = true;
  name = "polkadot-v${version}";
  version = "0.9.27";
  src = fetchFromGitHub {
    repo = "polkadot";
    owner = "paritytech";
    rev = "v${version}";
    hash = "sha256-LEz3OrVgdFTCnVwzU8C6GeEougaOl2qo7jS9qIdMqAM=";
  };
  cargoSha256 = "sha256-6y+WK2k1rhqMxMjEJhzJ26WDMKZjXQ+q3ca2hbbeLvA=";
  doCheck = false;
  buildInputs = [ openssl zstd ];
  nativeBuildInputs = [ rust-nightly clang pkg-config ]
    ++ lib.optional stdenv.isDarwin
    (with darwin.apple_sdk.frameworks; [ Security SystemConfiguration ]);
  LD_LIBRARY_PATH =
    lib.strings.makeLibraryPath [ stdenv.cc.cc.lib llvmPackages.libclang.lib ];
  LIBCLANG_PATH = "${llvmPackages.libclang.lib}/lib";
  PROTOC = "${protobuf}/bin/protoc";
  ROCKSDB_LIB_DIR = "${rocksdb}/lib";
  meta = { mainProgram = "polkadot"; };
}
```

**Comment by dzmitry-lahoda** [comment] 2022-10-04 20:04
try use `pkgs.rustPlatform.buildRustPackage`, not `crane`.

**Comment by dzmitry-lahoda** [comment] 2022-10-05 00:44
@ipetkov would be rigth to say `if pkgs.rustPlatform.buildRustPackage can build X then crane can build X because crane is superset of rustPlatform for building`, with assumption that `patches and substitute` or  full swap of pipeline not used.

**Comment by ipetkov** [comment] 2022-10-08 20:31
> would be rigth to say `if pkgs.rustPlatform.buildRustPackage can build X then crane can build X because crane is superset of rustPlatform for building`, with assumption that `patches and substitute` or full swap of pipeline not used.

Crane is an implementation that is completely distinct from `rustPlatform.buildRustPackage` and I cannot guarantee that they will be bug-for-bug compatible with each other.

I would imagine that the majority of cargo projects can successfully be built with both, but if a project's build script is not sandbox friendly (e.g. requires disabling chroot, or requires assuming that the crates are checked out from cargo's index in `$CARGO_HOME`) there will be friction trying to get things building
