### ISSUE TITLE
`doCheck = false` doesn't have any effect

### ISSUE THREAD

**Issue by MrFoxPro** [ipetkov/crane#558] opened 2024-03-21 10:54 UTC
Setting `doCheck = false;` for both `buildDepsOnly` and `buildPackage` anyway results in `cargo check` invocation when building dependencies. Only workaround I found is to set `cargoCheckCommand = "echo";`

**Comment by dpc** [comment] 2024-03-21 20:16
`doCheck` is a standard Nix command to run (or not) tests.

It's not about `cargo check`

**Comment by ipetkov** [comment] 2024-03-22 22:27
> Only workaround I found is to set `cargoCheckCommand = "echo";`

Yep this is the exact intended way to disable `cargo check` from within `buildDepsOnly` (you can replace that with `cargoCheckCommand = ":";` if you want to suppress the log statement entirely). As @dpc mentioned, `doCheck` influences whether `cargo test` is invoked

Gonna close this as this is by design, but feel free to reopen if you have other questions!

**Closed by ipetkov** 2024-03-22 22:27 UTC

**Comment by MrFoxPro** [comment] 2024-03-23 01:51
What about adding flag like doCargoCheck then?

**Comment by dpc** [comment] 2024-03-23 04:09
My advice: if some crane command doesn't do exactly what you want, just go straight to `mkCargoDerivation` and embrace doing everything yourself with it.

**Comment by ipetkov** [comment] 2024-03-23 05:17
> What about adding flag like doCargoCheck then?

Running `cargo check` is pretty benign for the majority of projects, and since `cargoCheckCommand` already allows for controlling it, I'm not sure the extra flag would add much benefit

**Comment by MrFoxPro** [comment] 2024-04-12 12:05
> > What about adding flag like doCargoCheck then?
> 
> Running `cargo check` is pretty benign for the majority of projects, and since `cargoCheckCommand` already allows for controlling it, I'm not sure the extra flag would add much benefit

Yes but I feel like it takes significantly more time to build because of `cargo check`? Or am I wrong?

**Comment by dpc** [comment] 2024-04-12 16:25
`cargo check` is generally much faster than `cargo build`, but yes, it takes some time. On the flip side, if you follow up with `cargo clippy` you do want to have `cargo check` done already.
