### ISSUE TITLE
`*-sys` dependencies being rebuilt every time

### ISSUE THREAD

**Issue by PistachioCake** [ipetkov/crane#684] opened 2024-08-22 06:08 UTC
Howdy! I'm new to Nix/NixOS/flakes, so I'm still trying to get my head around everything, but I love this project so far.

I'm trying to build a bevy project as a nix flake with crane. Every time I run `nix build`, it rebuilds `alsa-sys` and all crates that depend on it, since "`the env variable PKG_CONFIG_PATH changed`".

[Here is a minimal repro](https://github.com/PistachioCake/crane-rebuild). With this repo, I:
* ran `$ cargo build` and `$ nix build && nix log > output.1.log`,
* modified `src/main.rs` trivially, to force a rebuild, and then
* ran `$ cargo build` and `$ nix build && nix log > output.2.log` again.
The second invocation of `cargo build` only rebuilt the `crane repro` crate, but the second invocation of `nix build` (as you can see in `output.2.log`) rebuilt `alsa-sys`, since "`the env variable PKG_CONFIG_PATH changed`".

Note: I did set `NIX_OUTPATH_USED_AS_RANDOM_SEED`, as you suggest re: `bindgen` recompilation. It doesn't seem to help in this case.

How can I prevent `PKG_CONFIG_PATH` from changing, or prevent `alsa-sys` from being rebuilt in some other way? Thanks in advance!

Possibly related to #682.

**Comment by dpc** [comment] 2024-08-22 20:23
AFAIR, Use `strictDeps = true;` and don't change the set of `buildInputs`, `nativeBuildInputs` etc. between invocations.

**Comment by ipetkov** [comment] 2024-08-22 23:10
Hi @PistachioCake thank you for the report and the reproduction! I found the source of the issue, which is `buildPackage` adding `jq` to `nativeBuildInputs` which causes `PKG_CONFIG_PATH` to change and that triggers the rebuild.

This should be fixed with #685 !

**Closed** 2024-08-22 23:24 UTC
Labels: bug

**Comment by PistachioCake** [comment] 2024-08-22 23:34
Thanks @ipetkov! I switched to that branch in my `flake.nix` and it seemed to work great, both for this repro and for my bevy project.

Incidentally, what @dpc suggested also seemed to work. Specifically, applying the below patch also prevents rebuilding `alsa-sys`. Any chance either of you could explain why? Does setting `strictDeps = true` change the way Nix/crane handle adding dependencies, or is it something else?

```patch
diff --git a/flake.nix b/flake.nix
index a5704e6..a85622f 100644
--- a/flake.nix
+++ b/flake.nix
@@ -20,14 +20,14 @@
         rustToolchain = pkgs.rust-bin.stable.latest.default;
         craneLib = (crane.mkLib pkgs).overrideToolchain rustToolchain;
 
-        nativeBuildInputs = with pkgs; [ rustToolchain pkg-config alsaLib ];
-        buildInputs = with pkgs; [ ];
+        nativeBuildInputs = with pkgs; [ rustToolchain pkg-config ];
+        buildInputs = with pkgs; [ alsaLib ];
 
         src = craneLib.cleanCargoSource ./.;
         commonArgs = {
           inherit src buildInputs nativeBuildInputs;
           NIX_OUTPATH_USED_AS_RANDOM_SEED = "pistachiok";
-          # strictDeps = true;
+          strictDeps = true;
         };
         cargoArtifacts = craneLib.buildDepsOnly commonArgs;
         bin = craneLib.buildPackage (commonArgs // {
```

**Comment by dpc** [comment] 2024-08-23 15:41
> Any chance either of you could explain why?

IIRC lots of `-sys` crates will request a rebuild on a change to `PKG_CONFIG_PATH` via their `build.rs`. `strictDeps = true` causes Nix to be much more conservative about what goes in `PKG_CONFIG_PATH`, as Nix sets it up automatically for the derivation (I can't remember from which argument exactly, but `nativeBuildInputs`, I think, and then it's just a matter of ensuring that it doesn't change by keeping the set of packages that go into it.

**Comment by simonzkl** [comment] 2024-10-02 10:48
I get why `PKG_CONFIG_PATH` changing would invalidate a bunch of `-sys` crates, but I don't understand why having `jq` in `nativeBuildInputs` would change `PKG_CONFIG_PATH` on every single build, unless the `jq` derivation itself changed.

**Comment by ipetkov** [comment] 2024-10-03 23:36
@simonzkl because `craneLib.buildPackage` would bring in `jq` whereas `craneLib.buildDepsOnly` wouldn't. The `PKG_CONFIG_PATH` changes _relative to those two derivations_, so if any (dependency) build script happens to ask cargo to rebuild if the variable changes, then caching doesn't actually work
