### ISSUE TITLE
Warn about attributes that are being overwritten

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#241] opened 2023-02-17 19:19 UTC
Multiple of times already I've noticed that some things i was setting were thrown away, often after upgrades. Like - right now I figured out that `src = ;` in my invocation of `lib.craneLib.buildDepsOnly` are discarded. Oftentimes it kind of still works, but there are subtle differences, which leads to debugging and studying API.

In combination with a potential little bugs in `crane` itself that do sometimes happen, that can lead to a lot of wasted time. Right now I'm investigating why my deps get rebuilt on an unrelated file change. I first discovered that my own filter was not being used, but now it looks like `mkDummySrc` should have filtered out that file anyway, and I think I remember ther was an issue like that reported few weeks back (Edit: yeah #194).

**Comment by ipetkov** [comment] 2023-02-18 23:06
Do you have a concrete reproduction I could take a look at?

For what its worth there are very few places where crane overwrites things, the majority of the time defaults are injected only if missing from the args (e.g. we might overwrite `pname` but that shouldn't affect failing the build).

> Like - right now I figured out that src = ; in my invocation of lib.craneLib.buildDepsOnly are discarded

I'm not sure this observation is correct, [`buildDepsOnly` will delegate to `mkDummySrc`](https://github.com/ipetkov/crane/blob/cfb6efcfc706e21c84682171581168e591b265d9/lib/buildDepsOnly.nix#L31) which in turn [will use `args.src`](https://github.com/ipetkov/crane/blob/cfb6efcfc706e21c84682171581168e591b265d9/lib/mkDummySrc.nix#L91-L94). Though if you are explicitly setting `args.dummySrc` then perhaps the `src` argument will be ignored in favor of the explicit dummy source being set.

Generally speaking, each function should be documented in its behavior of inputs/defaults, though if something is amiss I'd be happy to correct it!

**Comment by dpc** [comment] 2023-02-19 00:59
> Do you have a concrete reproduction I could take a look at?

I was setting `src = ...;` in a `buildDepsOnly`. That's rather concrete. The `src` is discarded and surely the user had some misunderstanding, but will get no indication of it.

**Comment by ipetkov** [comment] 2023-02-19 04:52
> I was setting `src = ...;` in a `buildDepsOnly`. That's rather concrete. The `src` is discarded

I don't understand how it would be possible for `src` to be ignored as the derivation wouldn't have a source to build at all?

The only possible theories I have around this are:
* if `dummySrc` is set, in which case, yes `src` will be ignored
* if additional code running before the args are passed to `buildDepsOnly` somehow overwrites `src`

I can't offer additional insight without seeing the exact nix expression(s) which trigger this

**Comment by dpc** [comment] 2023-02-19 05:45
> if dummySrc is set, in which case, yes src will be ignored

This was it, plus my misunderstanding of `buildDepsOnly.nix` as I was reading it.

Sorry. :)

**Comment by dpc** [comment] 2023-02-19 06:11
But should `buildDepsOnly` warn if both `src` and `dummySrc` are set? :thinking:

**Comment by ipetkov** [comment] 2023-02-19 17:29
Probably not a bad idea to have, might at least save someone else some debugging trouble

**Comment by dpc** [comment] 2023-02-20 01:06
@ipetkov 

```
error: attribute 'src' missing

       at /nix/store/al4nbq72by831wrd5b1cf6l5z8m7mh9y-source/lib/crateNameFromCargoToml.nix:15:34:

           14|   src = args.src or throwMsg;
           15|   cargoToml = args.cargoToml or (args.src + "/Cargo.toml");
             |                                  ^
           16|   cargoTomlContents = args.cargoTomlContents or (
```

Seems like this `src` was actually used for something after all?

**Comment by ipetkov** [comment] 2023-02-20 01:16
`src` does get used in other places, it's only `buildDepsOnly` which can get away with not having it.

What's the rest of the code thats raising this error?

**Comment by dpc** [comment] 2023-02-20 01:39
Something werid happened here, and I'm unable to reproduce. After removing `src = ...;` I actually got:

```
error: unable to find `src` attribute. consider one of the following:                                                                                                                                                                  
       - set `cargoVendorDir = vendorCargoDeps { cargoLock = ./some/path/to/Cargo.lock; }`                         
       - set `cargoVendorDir = vendorCargoDeps { src = ./src/containing/cargo/lock/file; }`                                                                                                                                            
       - set `cargoVendorDir = null` to skip vendoring altogether 
```

now and had to add:

```
+          cargoVendorDir = craneLib.vendorCargoDeps { src = ./.; };
```

**Comment by dpc** [comment] 2023-02-20 01:43
Oh, I see what happened.

The

```
error: attribute 'src' missing

       at /nix/store/al4nbq72by831wrd5b1cf6l5z8m7mh9y-source/lib/crateNameFromCargoToml.nix:15:34:

           14|   src = args.src or throwMsg;
           15|   cargoToml = args.cargoToml or (args.src + "/Cargo.toml");
             |                                  ^
           16|   cargoTomlContents = args.cargoTomlContents or (
```

happens when both `src` and `version` are missing, and I've since added the `version` to places, so it doesn't fail with it.

@ipetkov

**Comment by ipetkov** [comment] 2023-02-20 19:55
Ah yes we have a number of different defaults which will peek at `src` (for example to set the crate name and version for the derivation). You'll likely have to specify them directly to avoid that behavior, though at that point you're going to converge exactly on the implementation of `buildDepsOnly`.

**Comment by ipetkov** [comment] 2023-03-01 01:04
Closing this as I we found the root cause of the issue in https://github.com/ipetkov/crane/issues/249

**Closed by ipetkov** 2023-03-01 01:04 UTC
