### ISSUE TITLE
Fails to build when using `CARGO_MANIFEST_DIR` in build script

### ISSUE THREAD

**Issue by xgroleau** [ipetkov/crane#292] opened 2023-04-06 20:06 UTC
When using a build script that uses the `CARGO_MANIFEST_DIR`, the build fails as if the variable is empty.
See [this repo](https://github.com/xgroleau/crane-manifest-dir-bug) for reproducing the bug.
It seems [nipkgs had a similar issue](https://github.com/NixOS/nixpkgs/issues/56808) previously.

Here is the  full error when trying to build when using `nix bulid .#example` in the provided repo.

```sh
error: builder for '/nix/store/45xx4ylgnm9yckm1r23hsfb5rdphqhx5-example-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       > cargo 1.67.0-nightly (eb5d35917 2022-11-17)
       > ++ command cargo build --release --message-format json-render-diagnostics
       >    Compiling example v0.1.0 (/build/source)
       > error: failed to run custom build command for `example v0.1.0 (/build/source)`
       >
       > Caused by:
       >   process didn't exit successfully: `/build/source/target/release/build/example-735b478458419584/build-script-build` (exit status: 101)
       >   --- stderr
       >   thread 'main' panicked at 'Failed to compile {:?}: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: /build/source/proto/example.proto: No such file or directory\n" }', build.rs:10:10
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       For full logs, run 'nix log /nix/store/45xx4ylgnm9yckm1r23hsfb5rdphqhx5-example-0.1.0.drv'
```

Note the line `the process didn't exit successfully: '/build/source/target/release/build/example-735b478458419584/build-script-build\'`, the path starts at root instead of inside the nix-store.

**Comment by ipetkov** [comment] 2023-04-07 15:32
Hi @xgroleau thanks for the report and the reproduction!

The issue here is due to setting `src = craneLib.cleanCargoSource (craneLib.path ./.);` in
https://github.com/xgroleau/crane-manifest-dir-bug/blob/c28890aa70ec961cd80548c3e403293f2645e5ee/flake.nix#L36

`cleanCargoSource` will only keep `*.rs`, *.toml`, and `Cargo.lock` files which ends up filtering out the `*.proto` files the project may be using. You can [customize the source filter to include additional files](https://crane.dev/source-filtering.html) which should fix the build! [(permalink)](https://github.com/ipetkov/crane/blob/65d3f6a3970cd46bef5eedfd458300f72c56b3c5/docs/source-filtering.md)

(Closing since this looks like a project configuration issue, but if I've gotten something wrong or you have more information/questions feel free to reopen!)

**Closed by ipetkov** 2023-04-07 15:32 UTC

**Comment by xgroleau** [comment] 2023-04-07 15:43
Yes that was it! Thanks a lot for the pointers. Sorry for wrongfully creating an issue!
