### ISSUE TITLE
Using "cleanCargoSource" with include_str and a non-rs file will break the build

### ISSUE THREAD

**Issue by TheNeikos** [ipetkov/crane#138] opened 2022-10-11 15:02 UTC
As the title says, currently it will also clean depended files.

I understand that this is not something that is easily fixed, but I believe all the information is there to get the information.

I wonder though if `cargo` is able to give this list itself, or if it can be computed for the case of `include_str!`

**Comment by dpc** [comment] 2022-10-11 19:44
`crane` needs to be able to figure out this list before it starts really touching and running anything, so there's probably no way to improve it.

**Comment by ipetkov** [comment] 2022-11-10 02:13
Closing as this is the intended behavior of `cleanCargoSource`, but feel free to reopen if you have other questions!

**Closed by ipetkov** 2022-11-10 02:13 UTC
