### ISSUE TITLE
How to install using default.nix method without flake.nix?

### ISSUE THREAD

**Issue by PlumpMath** [ipetkov/crane#302] opened 2023-04-16 16:43 UTC
Hi 
I'm trying to use crane in an environment without flake.nix. I have successfully installed the Rust environment and can compile it with 'cargo run'. However, I'm looking for a way to install it using only 'default.nix' (craneLib). I have imported the 'lib' folder correctly according to 'default.nix'. However, I'm getting the following error.

Thanks.

building '/nix/store/vziw9f0f5fmr0s5xzf10m04khg69m8xs-rust-a44-for-deps-0.1.0.drv'...
cargoVendorDir not set, will not automatically configure vendored sources
cargoArtifacts not set, will not reuse any cargo artifacts
unpacking sources
unpacking source archive /nix/store/8zngrbw0im9q5jb4n7cjjcn325553n8f-source
source root is source
patching sources
Executing configureCargoCommonVars
configuring
default configurePhase, nothing to do
building
++ command cargo --version
cargo 1.66.1
++ command cargo check --release --all-targets
   Compiling rust-a44-for v0.1.0 (/tmp/nix-build-rust-a44-for-deps-0.1.0.drv-0/source)
error: failed to run custom build command for `rust-a44-for v0.1.0 (/tmp/nix-build-rust-a44-for-deps-0.1.0.drv-0/source)`

Caused by:
  could not execute process `/tmp/nix-build-rust-a44-for-deps-0.1.0.drv-0/source/target/release/build/rust-a44-for-95bc98f7ce28db9b/build-script-ac8cfh66ddwx6sg6rr4yaz1h1mz40cas-dummy` (never executed)

Caused by:
  Permission denied (os error 13)
error: builder for '/nix/store/vziw9f0f5fmr0s5xzf10m04khg69m8xs-rust-a44-for-deps-0.1.0.drv' failed with exit code 101
error: 1 dependencies of derivation '/nix/store/nw5xycnqsf56r5ja8j66na4vc59bky48-rust-a44-for-0.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s621x1njczlj5n6bpra9z255kq5l7fxb-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/499a7yrz2ik77z3qzykzq9ap1hlx5ns0-home-manager-generation.drv' failed to build
/var/services/homes/gp

**Comment by ipetkov** [comment] 2023-04-16 20:09
Could you please provide a (hopefully) minimal reproduction of the issue? Please include the commits for `crane`, `nixpkgs`, as well as the configuration used to instantiate everything.

Judging from the log there is an issue running a build script, but I can't diagnose it any further than that without a reproduction

**Comment by PlumpMath** [comment] 2023-04-17 01:00
It is not possible to use flake.nix in a Synology NAS with Nix installed directly (without Docker). Therefore, there are issues when installing using the lib folder and ../pkgs references as written in default.nix. So, I plan to use a script that simply runs cargo run. There are no problems in other environments. Thank you.

**Comment by ipetkov** [comment] 2023-04-17 02:05
> As of now, it seems like there is no way, so let's just leave it as it is.

FWIW it _is_ possible to use `crane` without a `flake.nix`, but it does require the appropriate `fetchurl` and `import` expressions to wire things up outside of a flake (and then getting it into `home-manager`). I'll close this out for the time being but feel free to reopen if you have other questions in the future!

**Closed by ipetkov** 2023-04-17 02:05 UTC

**Comment by turboMaCk** [comment] 2023-10-21 13:21
For the record this is what I come up with. It's an overlay which doesn't require flakes.

```nix
self: super:
let
  crane-src = super.fetchFromGitHub {
    owner = "ipetkov";
    repo = "crane";
    rev = "758ae442227103fa501276e8225609a11c99718e";
    sha256 = "sha256-zXHwu104SQOxogkMgg+w22c3+zI/FvK83TAkfLmeKw0=";
  };

  eachSystem = systems: f:
    let
      # Merge together the outputs for all systems.
      op = attrs: system:
        let
          ret = f system;
          op = attrs: key: attrs //
                           {
                             ${key} = (attrs.${key} or { })
                                      // { ${system} = ret.${key}; };
                           }
          ;
        in
          builtins.foldl' op attrs (builtins.attrNames ret);
    in
      builtins.foldl' op { } systems;

  eachDefaultSystem = eachSystem [
    "aarch64-linux"
    "aarch64-darwin"
    "x86_64-darwin"
    "x86_64-linux"
  ];

  lib = self.callPackage crane-src {
    pkgs = super;
  };
in
{
  crane = eachDefaultSystem (system: {
    inherit lib;
  });
}
```

Perhaps it would make sense to decouple some of these things from flake.nix so out to simplify usage without flake. There are still use-cases which don't allow for flakes.

**Comment by ipetkov** [comment] 2023-10-21 15:50
It's not necessary to replicate all the flake definitions to use `crane` through an overlay.

We already have a `default.nix` at the root of the repo which is effectively the same as `mkLib` from the flake: import it and pass it an instance of `pkgs` (or the equivalent of `self`/`final` in the overlay example) and the rest of the functionality will be there!

**Comment by turboMaCk** [comment] 2023-10-21 15:58
Thanks fo reply @ipetkov

As you can see I'm using `default.nix` in particular this `callPackage` call will use `default.nix` by following the default behaviour.

```
lib = self.callPackage crane-src {
    pkgs = super;
  };
```

Anyway in my case I still need all of the `system` behaviour because I'm importing nix file from my project that is designed to be embedded in `flake.nix`. In my case I'm using flake for development but I can't use it for deployment.

But perhaps I can change my default.nix in the project so that it doesn't apply this internally:

```
  craneLib = crane.lib.${system};
```

but rather accepts `craneLib` as an argument. That way I guess I can avoid the need for flake like system stuff.

**Comment by ipetkov** [comment] 2023-10-21 16:02
I'd recommend using [`crane.mkLib pkgsOrEquivalent`](https://crane.dev/API.html#mklib) as a more "universal" entry point

`crane.lib.${system}` is basically a shorthand for that if you don't need to tailor a nixpkgs instantiation, but it seems like you're already doing that tailoring yourself

**Comment by turboMaCk** [comment] 2023-10-21 16:32
In case this helps someone this is what I landed on. First I have a `default.nix` in the project which can be either embedded directly in flake or used outside of it.

This commit shows the simplifications https://github.com/ictunion/main-system-public/commit/43d0fa5b922c7227a43a95babb1936fbdb1a9e17

Deployment stuff is not public but essentially I have this overlay:

```nix
self: super:
let
  crane-src = super.fetchFromGitHub {
    owner = "ipetkov";
    repo = "crane";
    rev = "758ae442227103fa501276e8225609a11c99718e";
    sha256 = "sha256-zXHwu104SQOxogkMgg+w22c3+zI/FvK83TAkfLmeKw0=";
  };
in
{
  craneLib = import crane-src {
    pkgs = super;
  };
}
```

and this somewhere in nixos module:

```nix
  # Backed API
  orca = (pkgs.callPackage "${pkgs.ictunion-system-src}/orca" {
    # Enable proxy sypport because we know we can trust nginx headers
    buildFeatures = [ "proxy-support" ];
  }).orca;
```
