### ISSUE TITLE
Build script cannot access files from workspace root

### ISSUE THREAD

**Issue by simonzkl** [ipetkov/crane#496] opened 2024-01-23 13:39 UTC
A build script (`build.rs`) in a workspace crate cannot access files outside its crate directory (e.g. `/shared/baz.txt` is inaccessible from `/bar` because only `/bar` by itself is copied to the nix store, without any other root workspace files.

This works fine in a regular `cargo build` but fails when building as a crane derivation.

**Example project:** https://github.com/simonzkl/crane-build-script

```rust
fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let text = std::fs::read_to_string("../shared/baz.txt").unwrap();
    std::fs::write(
        format!("{out_dir}/hello.rs"),
        format!(r#"pub fn hello() {{ print!("{text}") }}"#),
    )
    .unwrap();

    println!("cargo:rerun-if-changed=../shared/baz.txt");
}
```

**Steps to reproduce:**

- Working: `cargo build`
- Not working: `nix build`

Cargo dependencies packaged through git can also have this issue, which makes it difficult to work around.

**Comment by simonzkl** [comment] 2024-01-23 14:27
I would argue that this is not idiomatic, but it is technically supported by cargo. Note that this also breaks `cargo publish` because a crate is referencing files outside its `CARGO_MANIFEST_DIR`. A common workaround there is to symlink `/bar/shared -> /shared`. This workaround however does not work in crane.

**Comment by ipetkov** [comment] 2024-01-24 00:38
Hi @simonzkl thanks for the report!

The issue here is that `craneLib.cleanSource` will (by default) ignore any files except for `*.rs` and `*.toml` so the `.txt` file is being ignored.

Take a look at https://crane.dev/source-filtering.html on how to tune your source filter to include the necessary files. Hope this helps!

**Comment by simonzkl** [comment] 2024-01-24 08:37
Ah, you might be right there. The issue remains when building git dependencies with build scripts that reference files outside their manifest dir. I thought I reproduced the issue without having to use git dependencies, but it seems that was just because of `cleanSource`. I updated the example. It works fine with regular cargo, but breaks in nix.

Not sure if that's something crane should handle or not though. It's technically a valid setup when used as a git/path dependency, but not as a cargo crate (`cargo publish`).

**Comment by ipetkov** [comment] 2024-01-27 02:14
> I updated the example. It works fine with regular cargo, but breaks in nix.

Unfortunately this isn't something we can work around in `crane` as the way cargo has chosen to represent git dependencies does not match how crate vendoring works. Namely if you try to build this project using `cargo vendor` it will likely fail for the same reasons.

My best advice would be to either fix the issue upstream, or depend on your own fork which applies the necessary patch.

Even if we were to introduce a first class way of patching git dependencies (see https://github.com/ipetkov/crane/issues/473#issuecomment-1892507511) you would still need to apply the necessary patching to make things work, unfortunately.

For now I'm going to resolve this as a duplicate of #473, but thanks anyway for the report!

**Closed by ipetkov** 2024-01-27 02:14 UTC
